name: Modificar Arquivo Base Image

on:
  push:
    tags:
      - "*"

jobs:
  Changes:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout do Repositório Atual
        uses: actions/checkout@v2

      - name: Setup credentials to access private repositories
        run: git config --global url.https://${{ secrets.PAT_TOKEN }}@github.com/.insteadOf https://github.com/
      
      - name: Check for changes
        run: |
          repository="https://github.com/PedroPGuimaraes/image_base.git"
          branch_name="updateImageBase-${{ github.ref_name }}"

          git clone $repository
          git config --global user.email "p.guimaraes@4intelligence.ai"
          git config --global user.name "PedroPGuimaraes"

          cd image-base
          git checkout -b $branch_name

          if git ls-remote --exit-code origin $branch_name; then
            git pull origin $branch_name
          else
            echo "Branch remoto não encontrado."
          fi

          sed -i "s/\(updateImageBase@\)v[^'\"]*/\1${{ github.ref_name }}/" Dockerfile

          changes=$(git status --porcelain)
          if [[ -n "$changes" ]]; then
            git add .
            git commit -m "Update Dockerfiles"
            git push origin $branch_name
          else
            echo "No changes to commit."
          fi

  OpenPR:
      needs: Changes
      runs-on: ubuntu-latest
      steps:
        - name: Checkout private tools
          uses: actions/checkout@v3
        - name: Create PR
          run: |
            release=$(curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/pulls \
              -d '{"title":"Automaticly created PR","body":"Update branch release","head":"main","base":"updateImageBase-${{ github.ref_name }}"}' | jq '.number')
            echo "Created PR #${release}"
