name: Modificar Arquivo Base Image

on:
  push:
    tags:
      - "*"

jobs:
  update-base-image:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout do Repositório Atual
        uses: actions/checkout@v2

      - name: Setup credentials to access private repositories
        run: git config --global url.https://${{ secrets.PAT_TOKEN }}@github.com/.insteadOf https://github.com/
      
      - name: Check for changes
        run: |
          repository="https://github.com/PedroPGuimaraes/image_base.git"
          branch_name="branch-${{ github.ref_name }}"
          repository_name="image_base\.git@\"

          git clone $repository
          git config --global user.email "p.guimaraes@4intelligence.ai"
          git config --global user.name "PedroPGuimaraes"

          cd image_base
          git checkout -b $branch_name

          if git ls-remote --exit-code origin $branch_name; then
            git pull origin $branch_name
          else
            echo "Branch remoto não encontrado."
          fi

          sed -i 's/\($repository_name)v[^"]*"/\1${{ github.ref_name }}"/' Dockerfile

          changes=$(git status --porcelain)
          if [[ -n "$changes" ]]; then
            git add .
            git commit -m "Update Dockerfile"
            git push origin $branch_name
          else
            echo "No changes to commit."
          fi
          
      
      - name: Open Pull Request
        run: |
          pr_count=$(gh pr list --state open --base main --head 'branch-${{ github.ref_name }}' --limit 1 | wc -l)
          
          if [[ "$pr_count" -gt 0 ]]; then
            echo "There is already an open pull request. Exiting..."
            exit 0
          else
            cd image_base
            gh pr create --base main --head 'branch-${{ github.ref_name }}' --title "Update Dockerfile" --body "Changes in Dockerfile"
          fi
      
