name: Modificar Arquivo DevOps

on:
  push:
    branches:
      - main

jobs:
  modify-file:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout do Repositório Atual
        uses: actions/checkout@v2

      - name: Setup credentials to access private repositories
        run: git config --global url.https://${{ secrets.PAT_TOKEN }}@github.com/.insteadOf https://github.com/
      
      - name: Check for changes
        run: |
          git clone https://github.com/PedroPGuimaraes/image_base.git
          cd image_base
          git checkout DevOps
          git pull origin DevOps
          sed -i 's/"PedroPGuimaraes\/image_base.git@v2.0.0"/"PedroPGuimaraes\/image_base.git@v1.0.0"/g' Dockerfile
          changes=$(git status --porcelain)
          if [[ -n "$changes" ]]; then
            git add .
            git commit -m "Update Dockerfile"
            git push origin DevOps
          else
            echo "No changes to commit."
          fi
      
      - name: Open Pull Request
        run: |
          cd image_base
          pr_count=$(gh pr list --state open --base main --head DevOps --limit 1 | wc -l)
          if [[ "$pr_count" -gt 0 ]]; then
            echo "There is already an open pull request. Exiting..."
            exit 0
          else
            cd image_base
            gh pr create --base main --head DevOps --title "Update Dockerfile" --body "Changes in Dockerfile"
          fi
      
