name: Modificar Arquivo DevOps

on:
  push:
    branches:
      - main

jobs:
  modify-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório Atual
        uses: actions/checkout@v2

      - name: Setup credentials to access private repositories
        run: git config --global url.https://${{ secrets.PAT_TOKEN }}@github.com/.insteadOf https://github.com/
      
      - name: Git Add, Commit and Push
        run: |
          git clone https://github.com/PedroPGuimaraes/image_base.git

          cd image_base
          git config user.name "PedroPGuimaraes"
          git config user.email "p.guimaraes@4intelligence.ai"
          git checkout -b DevOps
          git pull DevOps
          sed -i 's/"PedroPGuimaraes\/image_base.git@v1.1.1"/"PedroPGuimaraes\/image_base.git@v1.0.0"/g' Dockerfile
          git add .
          git commit -m "Update Dockerfile"
          git push origin DevOps
      

#      - name: Open Pull Request using GitHub CLI
#        run: |
#          gh pr create --base main --head DevOps --title "Update Dockerfile" --body "Changes in Dockerfile"