name: Modificar Arquivo na Branch DevOps

on:
  push:
    branches:
      - main  # ou a branch que deseja monitorar

jobs:
  modify-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório Atual
        uses: actions/checkout@v2
        
      - name: Clone do Repositório Destino
        run: git clone https://github.com/PedroPGuimaraes/image_base.git
              
      - name: Criar e Mudar para a Branch DevOps
        run: |
          cd image_base
          git checkout -b DevOps
          cd image_base
          git status
          sed -i 's/"PedroPGuimaraes\/image_base.git@v1.0.0"/"PedroPGuimaraes\/image_base.git@v1.1.0"/g' Dockerfile
          git status
          git config --global user.email "p.guimaraes@4intelligence.ai"
          git config --global user.name "PedroPGuimaraes"
          git add .
          git commit -m "Atualizando arquivo via workflow na branch DevOps"
          git push origin DevOps
