name: Modificar Arquivo na Branch DevOps

on:
  push:
    branches:
      - main

jobs:
  modify-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório Atual
        uses: actions/checkout@v2
        
      - name: Git Add, Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git clone git@github.com:PedroPGuimaraes/update_image_base.git

          cd image_base
          git config user.name "PedroPGuimaraes"
          git config user.email "p.guimaraes@4intelligence.ai"

          git checkout -b DevOps

          git status
          sed -i 's/"PedroPGuimaraes\/image_base.git@v1.0.0"/"PedroPGuimaraes\/image_base.git@v1.1.0"/g' Dockerfile
          git status
          git add Dockerfile
          git commit -m "updated Dockerfile"

          git remote -v
          git push origin DevOps
